clc;
clear all;
close all;
pkg load signal;
t=[0:0.001:1];
f1=5;
m1=sin(2*pi*f1*t);
mh=hilbert(m1);
subplot(5,2,[1,2]);
plot(t,m1);
title('message');
xlabel("time");
ylabel("Amplitude");
f2=100;
c=sin(2*pi*f2*t);
ch=cos(2*pi*f2*t);
subplot(5,2,[3,4]);
plot(t,c);
title('carrier');
xlabel("time");
ylabel("Amplitude");
s1=((c.*m1)-(mh.*ch));
subplot(5,2,[5,6]);
plot(t,s1);
title('Upper SSB-SC ');
xlabel("time");
ylabel("Amplitude");
s2=((c.*m1)+(mh.*ch));
subplot(5,2,[7,8]);
plot(t,s2);
title('Lower SSB-SC');
xlabel("time");
ylabel("Amplitude");
d=s2.*c;
[b,a]=butter(5,0.1);
d1=filter(b,a,d);
subplot(5,2,[9,10]);
plot(t,d1);
title('demodulation');